<?php
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use App\Users;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $home="home";
    return view('presentation/welcome')->with(['home'=> $home]);
});

Route::get('/about', function () {
    $home="about";
    return view('presentation/about')->with('home', $home);
});

Route::get('/sendEmail', 'HomeController@sendEmail');

Route::get('/events', function () {
    $home="events";
    return view('presentation/events')->with('home', $home);
});

Route::get('/gallery', function () {
    $home="gallery";
    return view('presentation/gallery')->with('home', $home);
});

Route::get('/news', function () {
    $home="news";
    return view('presentation/news')->with('home', $home);
});

Route::get('/contact', function () {
    $home="contact";
    return view('presentation/contact')->with('home', $home);
});



//For the googlers, here is a full list of routes that are getting generated by Auth::routes(); in Laravel 5.4 (to 5.7)

// Authentication Routes...



Auth::routes();

Route::get('activate/{token}', 'Auth\RegisterController@activate')
    ->name('activate');

Route::group(['middleware'=>'auth'], function () {

    //enregistrer une image
    Route::post('/saveImg', 'PostsController@saveImg');
    //liste des postes
    Route::get('/posts','PostsController@postfeed');
    //supprimer un post
    Route::get('/deletePost/{id}', 'PostsController@deletePost');
    //modifier le status d'un message
    Route::get('/update_status_message/{id}', 'ProfileController@update_status_message'); 
    
    //liste du reseau (personne pas encore amis inscrit dans la plateforme)
    Route::get('/network', 'FriendshipsController@friends'); 

    Route::get('/connection_network', 'FriendshipsController@connection_network');
    Route::get('/test', 'FriendshipsController@connection_network'); //test
     //voir la liste des amis d'un utilisateurs
    Route::get('/view_network', 'FriendshipsController@view_network');
    Route::get('/is_friend', 'FriendshipsController@is_friend');
    Route::get('/getMessages', 'ProfileController@getMessages'); // Liste des messages
    Route::get('/getConversation/{id}', 'ProfileController@getConversation'); //liste des personnes evoyant des messages
    Route::get('/messages', 'ProfileController@messages'); //page des messages
    Route::get('/network/invitation', 'ProfileController@requestFriends'); //page des reponses aux invitations
    Route::get('/notifications', 'HomeController@notifications'); //notifications
    Route::get('check_realion_ship_status/{id}', 'FriendshipsController@check'); //le status entre un utilisateurs connecte et celui visitant son profil

    Route::get('/accept/{id}', 'FriendshipsController@acceptFriend'); //accepter unde demande d'amis
    //Route:get('/invitation', 'ProfileController@requestFriends');
    Route::get('/home', 'HomeController@index')->name('home'); //page daccueil
    Route::get('monprofil/{id}', 'ProfileController@myprofil'); // vue du profil
    Route::get('/addFriend/{id}', 'FriendshipsController@sendFriend'); // ajout d'une relation
    Route::post('/addPost', 'PostsController@addPost'); // ajouter des posts 
    Route::post('/sendCommentaire', 'PostsController@sendCommentaire'); // ajouter des commentaires
    Route::get('/testPost', 'PostsController@testPost');
    Route::post('/sendMsg', 'ProfileController@sendMsg'); //envoyer des messages
    Wizard::routes('wizard/user', 'UserWizardController', 'wizard.user'); //wizard tab pour inserer les donnees à la premiere connexion


    Route::get('get_unread', function () {
        Auth::user()->unreadNotifications()->get();
    });


    Route::get('get_auth_user_data', function(){
        return Auth::user();
    });

    Route::get('/like/{id}', 'LikesController@like');

    Route::get('/unlike/{id}', 'LikesController@unlike');

    
});
